spring:
  profiles:
    active: @profileActive@
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
      location: /tdpro/uploadcache
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
      host: 192.168.0.39
      port: 6379
      password:
      database: 13

server:
  port: 93
  tomcat:
    remote-ip-header: x-forwarded-for
    basedir: /tdpro/uploadtmp
  use-forward-headers: true

swagger:
  package: com.tdpro.controller

# MyBatis
mybatis:
      # 配置类型别名
      typeAliasesPackage: com.tdpro.entity/**
      # dao层接口
      basePackage: com.tdpro.mapper
      # 配置mapper的扫描，找到所有的mapper.xml映射文件
      mapperLocations: classpath:mybatis/mapper/*.xml
      # 加载全局的配置文件
      configLocation: classpath:mybatis/mybatis-config.xml

qiniu:
  imgPath: http://img.fumeiren.top/

wxconfig:
  appid: wxcfee96fb699a352d
  secret: b44e8c250f83dacb7d1752f3bea54784

com.tdpro.common.utils.jwt:
  tokenExpirationTime: 432000 # Number of minutes
  refreshTokenExpTime: 432000 # Minutes
  tokenIssuer: http://zerocat.cn
  tokenSigningKey: FpD5q^8cQ2uhta@voS0vZyEqk@1!KWoS
  headerString: tdProAuthor

blockerPath:
  userPath: /user/
  userIgnorePath: /user/userEnroll,/user/sms/enrollSend,/user/home/,/user/goods/
  adminPath: /api/
  notTokenPath: /api/login,/auth/login,/td/notify/,/swagger-ui.html,/webjars/,/swagger-resources/,/swagger-resources,/v2/api-docs,/user/sms/send

wechat:
  mainapp:
    appid: wx1d7c99f7945f0677 #wx390faf0b19fe5af2
    secret: 46752c7174dc19275f806cc891bc07db #8b6aabfc15cbfa26e866d542e6a166f9
#    appid: wx390faf0b19fe5af2
#    secret: 8b6aabfc15cbfa26e866d542e6a166f9
    token: G1X1jiil1iInLzl5iiRRzIjCnC1jiZ2a
    aesKey: KFwlcjWWSD8CsMxVlrS6s6FSws1NfpmFCrCpNsjnxdN

xxl:
  job:
    accessToken:
    executor:
      appname: tdpro-job
      port: 9999
      ip:
      logpath: /jobhandler
      logretentiondays: -1
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin



